spring:
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'andreyzorin494'
    password: 'GeekBrains'
    properties:
      mail:
        smtp:
          auth: 'true'
          starttls:
            enable: 'true'
